"use client";
import {Check,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {API_URL} from "../lib/api";
import type {Company} from "../lib/types";
import {Select} from "./Select";

type Debt={id:number;customer:string;amount:string;status:string;kind:string;businessId:number};

export function PaymentModal({company,close,done}:{company:Company;close:()=>void;done:(text:string)=>void}){
 const [debts,setDebts]=useState<Debt[]>([]),[debtId,setDebtId]=useState(""),[amount,setAmount]=useState(""),[document,setDocument]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch(`${API_URL}/api/debts?scope=${company}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("Не удалось загрузить задолженности");return response.json()}).then((items:Debt[])=>{const open=items.filter(item=>item.status!=="Закрыт"&&Number(item.amount.replace(/\D/g,""))>0);setDebts(open);if(open[0]){setDebtId(String(open[0].id));setAmount(open[0].amount)}}).catch(reason=>{if(reason.name!=="AbortError")setError(reason.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[company]);
 const selected=useMemo(()=>debts.find(item=>String(item.id)===debtId),[debts,debtId]);
 function choose(value:string){setDebtId(value);const debt=debts.find(item=>String(item.id)===value);setAmount(debt?.amount??"")}
 async function submit(){if(!selected||!amount.replace(/\D/g,"")){setError("Выбери задолженность и укажи сумму");return}setSaving(true);setError("");try{const response=await fetch(`${API_URL}/api/debts/payment`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({debtId:selected.id,amount,document:document.trim()||"Оплата"})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message??"Не удалось сохранить оплату");done(result.status==="Закрыт"?"Задолженность полностью закрыта":"Оплата сохранена, остаток пересчитан")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить оплату")}finally{setSaving(false)}}
 return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="payment-title"><div className="modalhead"><div><h2 id="payment-title">Регистрация оплаты</h2><small>Остаток задолженности изменится сразу после сохранения</small></div><button className="close" aria-label="Закрыть окно" onClick={close}><X/></button></div><div className="form"><div className="formgrid"><div className="field full"><label>Кредит / дебит</label><Select ariaLabel="Выбрать задолженность" value={debtId} onChange={choose} disabled={loading||!debts.length} options={debts.map(item=>({value:String(item.id),label:`${item.customer} · ${item.kind==="payable"?"кредит":"дебит"} · ${item.amount} сум`}))}/></div><label className="field"><label>Сумма оплаты, сум</label><input inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)} /></label><label className="field"><label>Документ или основание</label><input value={document} onChange={event=>setDocument(event.target.value)} placeholder="Платежное поручение" /></label></div>{!loading&&!debts.length&&<p className="stock-state">Открытых задолженностей нет</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="modalfoot"><button className="ghost" onClick={close}>Отмена</button><button className="primary" disabled={loading||saving||!selected} onClick={()=>void submit()}><Check/>{saving?"Сохраняем...":"Сохранить оплату"}</button></div></section></div>
}
