"use client";

import {useEffect,useState} from "react";
import {Save,X} from "lucide-react";
import {Select} from "../components/Select";
import {API_URL} from "../lib/api";
import type {Company} from "../lib/types";

const number=(value:string)=>Number(value.replace(/\D/g,""))||0;
type Form={businessCode:"import"|"retail";name:string;type:string;creditLimit:string;manager:string};
const blank=(company:Company):Form=>({businessCode:company==="retail"?"retail":"import",name:"",type:"Поставщик",creditLimit:"0",manager:""});

export function ClientsPage({rows,company,canCreate,onCreated,onSales,onDebts}:{rows:string[][];company:Company;canCreate:boolean;onCreated:()=>void;onSales:(filter:string)=>void;onDebts:()=>void}){
 const [form,setForm]=useState<Form|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const debit=rows.reduce((sum,row)=>sum+number(row[3]),0);
 useEffect(()=>{if(!form)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setForm(null)};document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[form]);
 async function save(){if(!form)return;setBusy(true);setError("");try{const response=await fetch(`${API_URL}/api/clients/counterparty`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message??`API ${response.status}`);setForm(null);onCreated()}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось добавить контрагента")}finally{setBusy(false)}}
 return <><div className="kpis counterparty-kpis"><button className="card kpi" onClick={onDebts}><small>Дебит - нам должны</small><strong>{debit.toLocaleString("ru-RU")} сум</strong><span>Открыть панель задолженностей</span></button><div className="card kpi"><small>Контрагенты</small><strong>{rows.length}</strong><span>Покупатели и партнеры</span></div></div><div className="toolbar"><span className="count">{rows.length} контрагентов</span><span className="spacer"/>{canCreate&&<button className="primary" onClick={()=>{setError("");setForm(blank(company))}}>Новый контрагент</button>}</div><div className="split">{rows.map(c=><button className="card debt-card interactive-client" key={c[0]} onClick={()=>onSales(c[0])}><div className="debt-head"><span className="company-logo">{c[0].split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><h3>{c[0]}</h3><p>{c[1]} · Ответственный: {c[5]}</p></div><div className="debt-amount"><strong>{c[3]} сум</strong><small>{c[3]==="0"?"Нет дебита":`до ${c[4]}`}</small></div></div><span className="open-hint">Открыть историю продаж</span></button>)}</div>
 {form&&<div className="modalback" onMouseDown={event=>{if(event.target===event.currentTarget)setForm(null)}}><div className="modal counterparty-modal" role="dialog" aria-modal="true" aria-labelledby="counterparty-title"><div className="modalhead"><div><h2 id="counterparty-title">Новый контрагент</h2><small>После сохранения контрагент появится в базе и списке производителей.</small></div><button className="close" aria-label="Закрыть окно" onClick={()=>setForm(null)}><X/></button></div><div className="form"><div className="formgrid">{company==="all"&&<div className="field full"><label>Компания</label><Select ariaLabel="Компания контрагента" value={form.businessCode} options={[{value:"import",label:"GARIK IMPORT"},{value:"retail",label:"GARIK RETAIL"}]} onChange={value=>setForm({...form,businessCode:value as "import"|"retail"})}/></div>}<div className="field full"><label>Название</label><input aria-label="Название" autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Тип</label><Select ariaLabel="Тип контрагента" value={form.type} options={[{value:"Поставщик",label:"Поставщик"},{value:"Производитель",label:"Производитель"},{value:"Покупатель",label:"Покупатель"},{value:"Партнер",label:"Партнер"}]} onChange={value=>setForm({...form,type:value})}/></div><div className="field"><label>Кредитный лимит, сум</label><input aria-label="Кредитный лимит, сум" inputMode="numeric" value={form.creditLimit} onChange={e=>setForm({...form,creditLimit:e.target.value.replace(/[^0-9]/g,"")})}/></div><div className="field full"><label>Ответственный</label><input aria-label="Ответственный" value={form.manager} onChange={e=>setForm({...form,manager:e.target.value})}/></div></div>{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="modalfoot"><button className="ghost" disabled={busy} onClick={()=>setForm(null)}>Отмена</button><button className="primary" disabled={busy||!form.name.trim()} onClick={()=>void save()}><Save/>{busy?"Сохранение...":"Добавить контрагента"}</button></div></div></div>}
 </>
}
