import {ArrowDownLeft,ArrowUpRight,CircleDollarSign, Plus, Search, WalletCards, X} from "lucide-react";
import {useEffect, useMemo, useState} from "react";
import {API_URL} from "../lib/api";

type Props={rows:string[][];canCreate:boolean;onCreate:()=>void;onPayment:()=>void;onMovements:(filter:string)=>void};
type HistoryRow={type:string;amount:string;occurredAt:string;document:string;note:string;product?:string};

export function DebtsPage({rows,canCreate,onCreate,onPayment,onMovements}:Props){
 const [query,setQuery]=useState(""),[history,setHistory]=useState<{name:string;rows:HistoryRow[]}|null>(null);
 const filtered=useMemo(()=>{const value=query.trim().toLocaleLowerCase("ru");return value?rows.filter(row=>row[0].toLocaleLowerCase("ru").includes(value)):rows},[query,rows]);
 const receivable=filtered.filter(row=>row[8]!=="payable"), payable=filtered.filter(row=>row[8]==="payable");
 async function openHistory(row:string[]){const response=await fetch(`${API_URL}/api/debts/history?businessId=${row[10]}&counterparty=${encodeURIComponent(row[0])}`);setHistory({name:row[0],rows:response.ok?await response.json():[]})}
 const total=(items:string[][])=>items.filter(row=>row[7]!=="Закрыт").reduce((sum,row)=>sum+Number(row[3].replace(/\D/g,"")),0);
 const money=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} сум`;
 return <><div className="debt-summary"><div><span className="debt-summary-icon debit"><ArrowDownLeft/></span><p>Дебит - нам должны</p><strong>{money(total(receivable))}</strong><small>{receivable.filter(row=>row[7]!=="Закрыт").length} открытых задолженностей</small></div><div><span className="debt-summary-icon credit"><ArrowUpRight/></span><p>Кредит - мы должны</p><strong>{money(total(payable))}</strong><small>{payable.filter(row=>row[7]!=="Закрыт").length} открытых задолженностей</small></div></div><div className="debt-toolbar"><label className="debt-search"><span>Поиск по контрагенту</span><span className="debt-search-control"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Например, LIQUI MOLY"/></span></label><div className="debt-actions">{canCreate&&<button className="primary" onClick={onCreate}><Plus/>Добавить долг</button>}<button className="ghost" onClick={onPayment}><CircleDollarSign/>Принять оплату</button></div></div><div className="debt-columns"><DebtColumn title="Дебит" hint="Нам должны покупатели и клиенты" icon={<WalletCards/>} rows={receivable} onHistory={openHistory} query={query}/><DebtColumn title="Кредит" hint="Мы должны поставщикам" icon={<CircleDollarSign/>} rows={payable} onHistory={openHistory} query={query}/></div>{history&&<HistoryModal {...history} onMovements={filter=>{setHistory(null);onMovements(filter)}} close={()=>setHistory(null)}/>}</>
}

function DebtColumn({title,hint,icon,rows,onHistory,query}:{title:string;hint:string;icon:React.ReactNode;rows:string[][];onHistory:(row:string[])=>void;query:string}){
 return <section className="card debt-column"><header><span className="debt-column-icon">{icon}</span><div><h2>{title}</h2><p>{hint}</p></div><b>{rows.length}</b></header>{rows.length===0?<div className="debt-empty"><p>{query?"По этому имени ничего не найдено":"Задолженностей пока нет"}</p><span>{query?"Измени поисковый запрос.":"Новый долг появится здесь после сохранения."}</span></div>:<div className="debt-list">{rows.map((r,i)=><button key={`${r[0]}-${r[4]}-${i}`} className="debt-item" onClick={()=>void onHistory(r)}><div className="debt-item-head"><strong>{r[0]}</strong><span className={`badge ${/Просрочен/.test(r[7])?"red":/Оплата принята|Закрыт/.test(r[7])?"green":""}`}>{/Оплата принята|Закрыт/.test(r[7])?"Закрыт":r[7]}</span></div><b>{r[3]} сум</b><dl><div><dt>Магазин</dt><dd>{r[1]}</dd></div><div><dt>Срок</dt><dd>{r[4]}</dd></div><div><dt>Ответственный</dt><dd>{r[5]}</dd></div></dl>{r[9]&&<p className="debt-comment">{r[9]}</p>}<span className="open-hint">История операций</span></button>)}</div>}</section>
}

function HistoryModal({name,rows,close,onMovements}:{name:string;rows:HistoryRow[];close:()=>void;onMovements:(filter:string)=>void}){
 useEffect(()=>{const key=(event:KeyboardEvent)=>event.key==="Escape"&&close();document.body.style.overflow="hidden";addEventListener("keydown",key);return()=>{document.body.style.overflow="";removeEventListener("keydown",key)}},[close]);
 return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal debt-history" role="dialog" aria-modal="true" aria-label={`История ${name}`}><header className="modalhead"><div><h2>{name}</h2><p>Новые операции показаны сверху</p></div><button className="iconbtn" onClick={close} aria-label="Закрыть"><X/></button></header><div className="history-list">{rows.map((row,index)=><article key={`${row.type}-${row.document}-${index}`} className={row.type==="supply"?"history-supply":""}><span className={`badge ${row.type==="payment"?"green":""}`}>{row.type==="payment"?"Оплата":row.type==="supply"?"Поступление":"Продажа в долг"}</span><div><strong>{row.type==="supply"?row.product:`${row.amount} сум`}</strong><p>{row.document} · {row.note}{row.type==="supply"?` · ${row.amount}`:""}</p>{row.type==="supply"&&<button className="history-link" onClick={()=>onMovements(row.product||name)}>История движения товара</button>}</div><time>{row.occurredAt}</time></article>)}</div>{!rows.length&&<div className="debt-empty"><p>История пока пуста</p></div>}</section></div>
}
