"use client";
import {useEffect,useState} from "react";
import {BriefcaseBusiness,CalendarDays,Mail,Phone,WalletCards,X} from "lucide-react";
import {API_URL} from "../lib/api";
import type {Company} from "../lib/types";

type Employee={id:number;name:string;role:string;phone:string;email:string;hiredAt:string|null;salary:number;status:string;business?:{name:string}};
const money=(value:number)=>`${value.toLocaleString("ru-RU")} сум`;
export function EmployeesPage({rows:_,company}:{rows:string[];company:Company}){
 const [employees,setEmployees]=useState<Employee[]>([]),[selected,setSelected]=useState<Employee|null>(null),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch(`${API_URL}/api/employees?scope=${company}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();setEmployees(await response.json());setError("")}).catch(reason=>{if(reason?.name!=="AbortError")setError("Не удалось загрузить сотрудников")});return()=>controller.abort()},[company]);
 useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setSelected(null);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[selected]);
 if(error)return <section className="card data-state" role="alert"><h2>Сотрудники временно недоступны</h2><p>{error}</p></section>;
 return <><div className="toolbar"><span className="count">{employees.length} сотрудников в доступном контуре</span></div><div className="report-grid employee-grid">{employees.map(person=><button className="card report employee-card" key={person.id} onClick={()=>setSelected(person)}><span className="company-logo">{person.name.split(" ").map(v=>v[0]).slice(0,2).join("")}</span><div><strong>{person.name}</strong><small>{person.role} · {person.business?.name??company.toUpperCase()}</small></div><span className="badge green">{person.status}</span></button>)}</div>{selected&&<div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><section className="modal employee-modal" role="dialog" aria-modal="true" aria-labelledby="employee-name"><div className="modalhead"><div><h2 id="employee-name">{selected.name}</h2><small>{selected.role} · {selected.business?.name}</small></div><button className="close" aria-label="Закрыть карточку сотрудника" onClick={()=>setSelected(null)}><X/></button></div><div className="employee-details"><Detail icon={Phone} label="Телефон" value={selected.phone||"Не указан"}/><Detail icon={Mail} label="Электронная почта" value={selected.email||"Не указана"}/><Detail icon={CalendarDays} label="Дата оформления" value={selected.hiredAt?new Date(selected.hiredAt).toLocaleDateString("ru-RU"):"Не указана"}/><Detail icon={BriefcaseBusiness} label="Должность и статус" value={`${selected.role} · ${selected.status}`}/><Detail icon={WalletCards} label="Зарплата" value={money(selected.salary)}/></div></section></div>}</>;
}
function Detail({icon:Icon,label,value}:{icon:React.ComponentType<{size?:number}>;label:string;value:string}){return <div><span><Icon/></span><p><small>{label}</small><strong>{value}</strong></p></div>}
