"use client";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import {ArrowDownRight,ArrowUpRight,Banknote,Building2,CalendarDays,CircleDollarSign,Landmark,ShoppingBag,Users,WalletCards} from "lucide-react";
import {Select} from "../components/Select";
import {API_URL} from "../lib/api";
import type {Company} from "../lib/types";
import {DataTable} from "./shared";
type Overview={available:number;payroll:number;supplierDebt:number;clientDebt:number;forecast:number;accounts:Array<{name:string;owner:string;balance:string;updatedAt:string}>;payrollItems:Array<{employeeName:string;amount:number;dueDate:string;status:string}>;sales:Array<{number:string;date:string;customer:string;store:string;warehouse:string;amount:string;paymentStatus:string}>;products:Array<{sku:string;name:string;units:number;revenue:number;cost:number;grossProfit:number;margin:number}>};
const money=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} сум`;
export function FinancePage({rows:_,company}:{rows:string[][];company:Company}){
 const params=useSearchParams(),selectedDate=params.get("date"),selectedYear=params.get("year"),selectedMonth=params.get("month");
 const [period,setPeriod]=useState(selectedDate?"day":selectedYear?"year":"month"),[overview,setOverview]=useState<Overview|null>(null),[error,setError]=useState("");
 const filterQuery=selectedDate?`&date=${selectedDate}`:selectedYear?`&year=${selectedYear}${selectedMonth?`&month=${selectedMonth}`:""}`:"";
 useEffect(()=>{const controller=new AbortController();fetch(`${API_URL}/api/finance/overview?scope=${company}&period=${period}${filterQuery}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();setOverview(await response.json());setError("")}).catch(reason=>{if(reason?.name!=="AbortError")setError("Не удалось загрузить данные кассы")});return()=>controller.abort()},[company,period,filterQuery]);
 if(error)return <section className="card data-state" role="alert"><h2>Касса временно недоступна</h2><p>{error}</p><button className="primary" onClick={()=>location.reload()}>Повторить</button></section>;
 if(!overview)return <section className="card data-state" role="status"><h2>Считаем остатки</h2><p>Получаем счета, обязательства и продажи из базы</p></section>;
 const context=selectedDate?`За ${new Date(`${selectedDate}T00:00:00`).toLocaleDateString("ru-RU")}`:selectedYear?(selectedMonth?`За ${selectedMonth}.${selectedYear}`:`За ${selectedYear} год`):"Текущий период";
 const saleRows=overview.sales.map(x=>[x.number,x.date,x.customer,x.store||x.warehouse,x.amount,x.paymentStatus]);
 const productRows=overview.products.map(x=>[x.name,String(x.units),money(x.revenue),money(x.grossProfit),`${x.margin}%`]);
 return <div className="cash-page">
  <section className="cash-hero"><div><span className="cash-eyebrow"><CalendarDays/> {context}</span><h2>Деньги под контролем</h2><p>Живой остаток по счетам с учетом ближайших обязательств и ожидаемых оплат.</p></div>{!selectedDate&&!selectedYear&&<Select ariaLabel="Период кассы" value={period} onChange={setPeriod} options={[{value:"week",label:"7 дней"},{value:"month",label:"30 дней"},{value:"year",label:"12 месяцев"}]}/>}<div className="cash-balance"><small>Доступно сейчас</small><strong>{money(overview.available)}</strong><span className={overview.forecast>=0?"positive":"negative"}>{overview.forecast>=0?<ArrowUpRight/>:<ArrowDownRight/>} После обязательств: {money(overview.forecast)}</span></div></section>
  <section className="cash-flow" aria-label="Расчет прогнозного остатка"><Flow icon={Banknote} label="Доступно" value={overview.available}/><i>-</i><Flow icon={Users} label="Зарплаты" value={overview.payroll}/><i>-</i><Flow icon={ShoppingBag} label="Поставщикам" value={overview.supplierDebt}/><i>+</i><Flow icon={WalletCards} label="От клиентов" value={overview.clientDebt}/><i>=</i><Flow icon={CircleDollarSign} label="Прогноз" value={overview.forecast} accent/></section>
  <div className="cash-grid"><section className="cash-panel"><header><div><h3>Счета и кассы</h3><p>Где находятся доступные деньги</p></div><b>{overview.accounts.length}</b></header><div className="cash-account-list">{overview.accounts.map(account=><article key={account.name+account.owner}><span><Landmark/></span><div><strong>{account.name}</strong><small>{account.owner} · обновлено {account.updatedAt}</small></div><b>{account.balance} сум</b></article>)}</div></section><section className="cash-panel"><header><div><h3>Ближайшие выплаты</h3><p>Зарплаты и обязательства</p></div><b>{overview.payrollItems.length}</b></header>{overview.payrollItems.length?<div className="cash-account-list">{overview.payrollItems.map(item=><article key={item.employeeName+item.dueDate}><span><Building2/></span><div><strong>{item.employeeName}</strong><small>Срок {new Date(item.dueDate).toLocaleDateString("ru-RU")} · {item.status}</small></div><b>{money(item.amount)}</b></article>)}</div>:<div className="cash-empty">Нет ожидающих выплат</div>}</section></div>
  <section className="cash-table"><header><div><h3>Продажи</h3><p>Операции за выбранный период</p></div><b>{saleRows.length}</b></header>{saleRows.length?<DataTable headers={["Документ","Дата","Контрагент","Магазин","Сумма","Статус"]} rows={saleRows}/>:<div className="cash-empty">За этот период продаж нет</div>}</section>
  <section className="cash-table"><header><div><h3>Что приносит деньги</h3><p>Товары по выручке и валовой прибыли</p></div><b>{productRows.length}</b></header>{productRows.length?<DataTable headers={["Товар","Продано","Выручка","Прибыль","Маржа"]} rows={productRows}/>:<div className="cash-empty">Недостаточно данных для аналитики</div>}</section>
 </div>;
}
function Flow({icon:Icon,label,value,accent=false}:{icon:React.ComponentType<{size?:number}>;label:string;value:number;accent?:boolean}){return <div className={accent?"accent":""}><span><Icon/></span><small>{label}</small><strong>{money(value)}</strong></div>}
