"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {ArrowDownRight,ArrowUpRight,Building2,CalendarDays,Landmark,MinusCircle,PlusCircle,Search,X} from "lucide-react";
import {Select} from "../components/Select";
import {API_URL} from "../lib/api";
import type {Company} from "../lib/types";
import {DataTable} from "./shared";
type Line={sku:string;name:string;quantity:number;revenue:number;cost:number;profit:number;margin:number;markup:number};
type SaleDetails={number:string;date:string;customer:string;store:string;amount:number;paymentStatus:string;lines:Line[]};
type Account={id:number;name:string;owner:string;balance:string;updatedAt:string};
type Segment={name:string;value:number;percent:number};
type ProductRow={sku:string;name:string;units:number;revenue:number;cost:number;grossProfit:number;margin:number;markup:number};
type SectionBreakdown={business:string;total:number;cost:number;profit:number;items:Segment[];products:ProductRow[]};
type Overview={available:number;payroll:number;supplierDebt:number;clientDebt:number;forecast:number;accounts:Account[];payrollItems:Array<{employeeName:string;amount:number;dueDate:string;status:string}>;sales:Array<{number:string;date:string;customer:string;store:string;warehouse:string;amount:string;paymentStatus:string}>;products:ProductRow[];cashFlow:{income:number;expense:number;incomePercent:number;expensePercent:number;categories:Array<{type:string;name:string;amount:number}>};profitAnalysis?:{grossProfit:number;totalSales:number;segments:Segment[];productBreakdown:SectionBreakdown[]};transactions:Array<{id:number;type:string;amount:number;purpose:string;category:string;occurredAt:string;account:string}>};
const money=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} сум`;
export function FinancePage({rows:_,company}:{rows:string[][];company:Company}){
 const params=useSearchParams(),router=useRouter(),selectedDate=params.get("date"),selectedYear=params.get("year"),selectedMonth=params.get("month"),selectedSale=params.get("sale");
 const [period,setPeriod]=useState(selectedDate?"day":selectedYear?"year":"month"),[overview,setOverview]=useState<Overview|null>(null),[error,setError]=useState(""),[section,setSection]=useState<SectionBreakdown|null>(null),[product,setProduct]=useState<Overview["products"][number]|null>(null),[sale,setSale]=useState<SaleDetails|null>(null),[operation,setOperation]=useState<"income"|"expense"|null>(null),[reload,setReload]=useState(0);
 const filterQuery=selectedDate?`&date=${selectedDate}`:selectedYear?`&year=${selectedYear}${selectedMonth?`&month=${selectedMonth}`:""}`:"";
 useEffect(()=>{const controller=new AbortController();fetch(`${API_URL}/api/finance/overview?scope=${company}&period=${period}${filterQuery}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();setOverview(await response.json());setError("")}).catch(reason=>{if(reason?.name!=="AbortError")setError("Не удалось загрузить данные кассы")});return()=>controller.abort()},[company,period,filterQuery,reload]);
 useEffect(()=>{if(!selectedSale)return;const controller=new AbortController();fetch(`${API_URL}/api/sales/${encodeURIComponent(selectedSale)}/details?scope=${company}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();setSale(await response.json())}).catch(reason=>{if(reason?.name!=="AbortError")setError("Не удалось открыть выбранную продажу")});return()=>controller.abort()},[company,selectedSale]);
 useEffect(()=>{if(!sale&&!section&&!product&&!operation)return;const close=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(sale){setSale(null);router.replace("/finance",{scroll:false})}else if(product)setProduct(null);else if(section)setSection(null);else setOperation(null)};document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[sale,section,product,operation,router]);
 const closeSale=()=>{setSale(null);const next=new URLSearchParams(params.toString());next.delete("sale");router.replace(`/finance${next.size?`?${next}`:""}`,{scroll:false})};
 if(error&&!overview)return <section className="card data-state" role="alert"><h2>Касса временно недоступна</h2><p>{error}</p><button className="primary" onClick={()=>setReload(value=>value+1)}>Повторить</button></section>;
 if(!overview)return <section className="card data-state" role="status"><h2>Считаем остатки</h2><p>Получаем счета, обязательства и продажи из базы</p></section>;
 const context=selectedDate?`За ${new Date(`${selectedDate}T00:00:00`).toLocaleDateString("ru-RU")}`:selectedYear?(selectedMonth?`За ${selectedMonth}.${selectedYear}`:`За ${selectedYear} год`):"Текущий период";
 const profitAnalysis=overview.profitAnalysis??{grossProfit:overview.products.reduce((sum,x)=>sum+x.grossProfit,0),totalSales:overview.products.reduce((sum,x)=>sum+x.revenue,0),segments:[],productBreakdown:[]};
 const saleRows=overview.sales.map(x=>[x.number,x.date,x.customer,x.store||x.warehouse,x.amount,x.paymentStatus]);
 return <div className="cash-page">
  <section className="cash-hero"><div><span className="cash-eyebrow"><CalendarDays/> {context}</span><h2>Деньги под контролем</h2><p>Живой остаток, месячная структура доходов и расходов.</p></div><div className="cash-actions"><button className="cash-action-income" onClick={()=>setOperation("income")}><PlusCircle/>Внести средства</button><button className="cash-action-expense" onClick={()=>setOperation("expense")}><MinusCircle/>Списать средства</button></div>{!selectedDate&&!selectedYear&&<Select ariaLabel="Период кассы" value={period} onChange={setPeriod} options={[{value:"week",label:"7 дней"},{value:"month",label:"30 дней"},{value:"year",label:"12 месяцев"}]}/>}<div className="cash-balance"><small>Доступно сейчас</small><strong>{money(overview.available)}</strong><span className={overview.forecast>=0?"positive":"negative"}>{overview.forecast>=0?<ArrowUpRight/>:<ArrowDownRight/>} После обязательств: {money(overview.forecast)}</span></div></section>
  <section className="cash-monthly"><div><small>Доходы</small><strong>{money(overview.cashFlow.income)}</strong><span>{overview.cashFlow.incomePercent}% оборота</span><i style={{width:`${overview.cashFlow.incomePercent}%`}}/></div><div><small>Расходы</small><strong>{money(overview.cashFlow.expense)}</strong><span>{overview.cashFlow.expensePercent}% оборота</span><i style={{width:`${overview.cashFlow.expensePercent}%`}}/></div><ul>{overview.cashFlow.categories.filter(x=>x.amount>0).map(item=><li key={`${item.type}-${item.name}`}><span>{item.name}</span><b>{money(item.amount)}</b><em>{item.type==="income"?"Доход":"Расход"}</em></li>)}</ul></section>
  <section className="profit-analysis"><header><div><h3>Анализ продаж</h3><p>Актуальная выручка из продаж GARIK IMPORT и GARIK RETAIL</p></div><strong>{money(profitAnalysis.totalSales)}</strong></header><div className="profit-charts"><Donut title="Доход от продаж по секциям" items={profitAnalysis.segments} large/>{profitAnalysis.productBreakdown.map(group=><Donut key={group.business} title={`Продажи - ${group.business}`} items={group.items} onClick={()=>setSection(group)}/>)}</div></section>
  <div className="cash-grid"><section className="cash-panel"><header><div><h3>Счета и кассы</h3><p>Где находятся доступные деньги</p></div><b>{overview.accounts.length}</b></header><div className="cash-account-list">{overview.accounts.map(account=><article key={account.id}><span><Landmark/></span><div><strong>{account.name}</strong><small>{account.owner} · обновлено {account.updatedAt}</small></div><b>{account.balance} сум</b></article>)}</div></section><section className="cash-panel"><header><div><h3>Ближайшие выплаты</h3><p>Зарплаты и обязательства</p></div><b>{overview.payrollItems.length}</b></header>{overview.payrollItems.length?<div className="cash-account-list">{overview.payrollItems.map(item=><article key={item.employeeName+item.dueDate}><span><Building2/></span><div><strong>{item.employeeName}</strong><small>Срок {new Date(item.dueDate).toLocaleDateString("ru-RU")} · {item.status}</small></div><b>{money(item.amount)}</b></article>)}</div>:<div className="cash-empty">Нет ожидающих выплат</div>}</section></div>
  <section className="cash-table"><header><div><h3>Продажи</h3><p>Нажми на строку, чтобы открыть состав продажи</p></div><b>{saleRows.length}</b></header>{saleRows.length?<DataTable headers={["Документ","Дата","Контрагент","Магазин","Сумма","Статус"]} rows={saleRows} onRowClick={row=>router.replace(`/finance?sale=${encodeURIComponent(row[0])}`,{scroll:false})}/>:<div className="cash-empty">За этот период продаж нет</div>}</section>
  {overview.transactions.length>0&&<section className="cash-table"><header><div><h3>Ручные операции</h3><p>Категория месячного отчета - Остальное</p></div><b>{overview.transactions.length}</b></header><DataTable headers={["Дата","Касса","Назначение","Категория","Тип","Сумма"]} rows={overview.transactions.map(x=>[new Date(x.occurredAt).toLocaleDateString("ru-RU"),x.account,x.purpose,x.category,x.type==="income"?"Внесение":"Списание",money(x.amount)])}/></section>}
  {selectedSale&&sale&&<SaleModal sale={sale} close={closeSale}/>} {section&&<SectionModal section={section} close={()=>setSection(null)} openProduct={setProduct}/>} {product&&<ProductModal product={product} sales={overview.sales} close={()=>setProduct(null)}/>} {operation&&<CashOperationModal type={operation} accounts={overview.accounts} close={()=>setOperation(null)} done={()=>{setOperation(null);setReload(value=>value+1)}}/>}
 </div>;
}
const chartColors=["#2a7455","#6d9dde","#d59a32","#9b6fc2","#d8685d","#4f9fa2"];
function Donut({title,items,large=false,onClick}:{title:string;items:Segment[];large?:boolean;onClick?:()=>void}){const visible=items.filter(x=>large?x.value>0:x.value>=0),total=visible.reduce((sum,x)=>sum+x.value,0);const stops=visible.map((item,index)=>{const start=visible.slice(0,index).reduce((sum,x)=>sum+(total?x.value*360/total:0),0),end=start+(total?item.value*360/total:0);return `${chartColors[index%chartColors.length]} ${start}deg ${end}deg`});return <article className={`donut-card ${large?"large":""} ${onClick?"interactive":""}`} onClick={onClick} onKeyDown={event=>{if(onClick&&(event.key==="Enter"||event.key===" "))onClick()}} role={onClick?"button":undefined} tabIndex={onClick?0:undefined}><h4>{title}</h4>{visible.length&&total>0?<><div className="donut" role="img" aria-label={`${title}: ${visible.map(x=>`${x.name} ${x.percent}%`).join(", ")}`} style={{background:`conic-gradient(${stops.join(",")})`}}>{large&&<span><b>{visible.length}</b><small>секции</small></span>}</div><ul>{visible.map((item,index)=><li key={item.name}><i style={{background:chartColors[index%chartColors.length]}}/><span title={item.name}>{item.name}</span><b>{large?money(item.value):`${item.percent}%`}</b></li>)}</ul></>:<p className="donut-empty">За период нет продаж</p>}</article>}
function SectionModal({section,close,openProduct}:{section:SectionBreakdown;close:()=>void;openProduct:(product:ProductRow)=>void}){const [query,setQuery]=useState("");const products=section.products.filter(item=>`${item.name} ${item.sku}`.toLowerCase().includes(query.trim().toLowerCase()));return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal section-sales-modal" role="dialog" aria-modal="true" aria-labelledby="section-sales-title"><div className="modalhead"><div><h2 id="section-sales-title">Продажи - {section.business}</h2><small>Данные рассчитаны из актуальных продаж и партий БД</small></div><button className="close" aria-label="Закрыть аналитику секции" onClick={close}><X/></button></div><div className="profit-details">{[["Выручка",money(section.total)],["Себестоимость",money(section.cost)],["Валовая прибыль",money(section.profit)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><label className="cash-search"><Search/><span className="sr-only">Поиск товара</span><input aria-label="Поиск товара по названию или SKU" placeholder="Название или SKU / артикул" value={query} onChange={event=>setQuery(event.target.value)}/></label>{products.length?<DataTable hiddenColumns={[1]} headers={["Артикул","Товар","Продано","Выручка","Себестоимость","Прибыль","Маржа","Наценка"]} rows={products.map(x=>[x.sku,x.name,String(x.units),money(x.revenue),money(x.cost),money(x.grossProfit),`${x.margin}%`,`${x.markup}%`])} onRowClick={row=>{const selected=products.find(item=>item.sku===row[0]);if(selected)openProduct(selected)}}/>:<div className="cash-empty">За этот период продаж нет</div>}</section></div>}
function SaleModal({sale,close}:{sale:SaleDetails;close:()=>void}){return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal sale-details" role="dialog" aria-modal="true" aria-labelledby="sale-title"><div className="modalhead"><div><h2 id="sale-title">Продажа {sale.number}</h2><small>{sale.customer} · {sale.date} · {sale.store}</small></div><button className="close" aria-label="Закрыть продажу" onClick={close}><X/></button></div><DataTable headers={["Артикул","Товар","Количество","Выручка","Себестоимость","Прибыль","Маржа","Наценка"]} hiddenColumns={[1]} rows={sale.lines.map(x=>[x.sku,x.name,String(x.quantity),money(x.revenue),money(x.cost),money(x.profit),`${x.margin}%`,`${x.markup}%`])}/></section></div>}
function ProductModal({product,sales,close}:{product:Overview["products"][number];sales:Overview["sales"];close:()=>void}){return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal product-profit-modal" role="dialog" aria-modal="true" aria-labelledby="product-profit-title"><div className="modalhead"><div><h2 id="product-profit-title">{product.name}</h2><small>SKU / артикул: {product.sku}</small></div><button className="close" aria-label="Закрыть аналитику товара" onClick={close}><X/></button></div><div className="profit-details">{[["Продано",`${product.units} ед.`],["Выручка",money(product.revenue)],["Себестоимость",money(product.cost)],["Прибыль",money(product.grossProfit)],["Маржа",`${product.margin}%`],["Наценка",`${product.markup}%`]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><h3>Связанные продажи периода</h3><div className="related-sales">{sales.map(item=><span key={item.number}>{item.number} · {item.customer} · {item.date}</span>)}</div></section></div>}
function CashOperationModal({type,accounts,close,done}:{type:"income"|"expense";accounts:Account[];close:()=>void;done:()=>void}){const [account,setAccount]=useState(String(accounts[0]?.id??"")),[amount,setAmount]=useState(""),[purpose,setPurpose]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState(""),[saving,setSaving]=useState(false);async function submit(){if(!account||Number(amount)<=0||!purpose.trim()){setError("Выбери кассу, укажи сумму и назначение");return}setSaving(true);setError("");try{const response=await fetch(`${API_URL}/api/finance/transactions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cashAccountId:Number(account),type,amount:Number(amount),purpose,occurredAt:`${date}T12:00:00Z`})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message??"Не удалось сохранить операцию");done()}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить операцию")}finally{setSaving(false)}}return <div className="modalback" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal cash-operation-modal" role="dialog" aria-modal="true" aria-labelledby="cash-operation-title"><div className="modalhead"><div><h2 id="cash-operation-title">{type==="income"?"Внести средства":"Списать средства"}</h2><small>Операция попадет в месячный отчет как «Остальное»</small></div><button className="close" aria-label="Закрыть форму" onClick={close}><X/></button></div><div className="form"><div className="formgrid"><label className="field"><span>Касса или счет</span><Select ariaLabel="Касса или счет" value={account} onChange={setAccount} options={accounts.map(x=>({value:String(x.id),label:x.name,secondary:`${x.balance} сум`}))}/></label><label className="field"><span>Сумма, сум</span><input type="number" min="1" inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="field"><span>Дата операции</span><input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="field full"><span>Назначение</span><input value={purpose} onChange={event=>setPurpose(event.target.value)} placeholder="Например, возврат займа или хозяйственные расходы"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="modalfoot"><button className="ghost" onClick={close}>Отмена</button><button className="primary" disabled={saving} onClick={()=>void submit()}>{saving?"Сохраняем...":type==="income"?"Внести":"Списать"}</button></div></section></div>}
