"use client";
import {Store,Warehouse,X} from "lucide-react";
import {useEffect,useState} from "react";
import type {Company} from "../lib/types";
import {API_URL} from "../lib/api";

type Stock={id:number;warehouseName:string;sku:string;productName:string;quantity:number;expectedIncoming:number;expectedOutgoing:number;remainingAfterOutgoing:number;purchasePrice:number;purchaseValue:number;retailPrice:number;retailValue:number};
type Movement={id:number;number:string;operation:string;source:string;destination:string;date:string;status:string;productSku:string;productName:string;batchNumber:string;quantity:number};
const money=(value:number)=>`${value.toLocaleString("ru-RU")} сум`;

export function WarehousesPage({rows,company,onMovements}:{rows:string[][];company:Company;onMovements:(filter:string)=>void}){
 const [selected,setSelected]=useState<string|null>(null),[allStocks,setAllStocks]=useState<Stock[]>([]),[movements,setMovements]=useState<Movement[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const stocks=allStocks.filter(x=>x.warehouseName===selected);
 useEffect(()=>{const controller=new AbortController();Promise.all([fetch(`${API_URL}/api/warehouse-stocks/valuation?scope=${company}`,{signal:controller.signal}),fetch(`${API_URL}/api/movements/search?scope=${company}`,{signal:controller.signal})]).then(async responses=>{if(responses.some(r=>!r.ok))throw new Error();return [await responses[0].json() as Stock[],await responses[1].json() as Movement[]] as const}).then(([stockRows,movementRows])=>{setAllStocks(stockRows);setMovements(movementRows);setError("")}).catch(e=>{if(e.name!=="AbortError")setError("Не удалось загрузить данные склада")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[company]);
 useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[selected]);
 const retailTotal=stocks.reduce((sum,item)=>sum+item.retailValue,0);
 function showMovements(product:Stock,mode:"stock"|"incoming"|"outgoing"){
  setSelected(null);
  const params=new URLSearchParams({sku:product.sku,warehouse:product.warehouseName});
  if(mode!=="stock")params.set("operation",mode);
  onMovements(params.toString());
 }
 const incoming=movements.filter(x=>x.destination===selected&&x.operation==="Поступление"),outgoing=movements.filter(x=>x.source===selected&&(x.operation==="Отгрузка"||x.operation==="Перемещение"));
 const selectedWarehouse=rows.find(row=>row[0]===selected),selectedUsed=Number(selectedWarehouse?.[6]??0),selectedTotal=Number(selectedWarehouse?.[5]??0),selectedNote=selectedWarehouse?.[7]??"Замечание складовщика не добавлено";
 return <><div className="toolbar"><span className={`business-chip company-${company}`}>{rows.length} складских точек</span><span className="spacer"/><span className="count">Нажми на склад, затем на товар</span></div><div className="warehouse-grid">{rows.map(w=>{const warehouseStocks=allStocks.filter(x=>x.warehouseName===w[0]),quantity=warehouseStocks.reduce((sum,x)=>sum+x.quantity,0),purchaseValue=warehouseStocks.reduce((sum,x)=>sum+x.purchaseValue,0),retailValue=warehouseStocks.reduce((sum,x)=>sum+x.retailValue,0),capacityTotal=Number(w[5]??0),capacityUsed=Number(w[6]??0),capacityPercent=capacityTotal>0?Math.min(100,Math.round(capacityUsed*100/capacityTotal)):0;return <button className="card warehouse warehouse-button" key={w[0]} onClick={()=>setSelected(w[0])}><div className="warehouse-head"><span className="warehouse-icon">{/магазин/i.test(w[0])?<Store/>:<Warehouse/>}</span><span className="badge">Активен</span></div><h3>{w[0]}</h3><p>{w[1]}</p><div className="warehouse-stats warehouse-value-stats"><div className="mini"><small>Остаток</small><strong>{loading?"…":`${quantity} ед.`}</strong></div><div className="mini"><small>Закупочная стоимость</small><strong>{loading?"…":money(purchaseValue)}</strong></div><div className="mini"><small>Розничная стоимость</small><strong>{loading?"…":money(retailValue)}</strong></div></div><div className="warehouse-capacity"><div><small>Приблизительная вместимость</small><strong>~{capacityUsed} / {capacityTotal} ед.</strong></div><div className="progress" aria-label={`Склад заполнен на ${capacityPercent}%`}><span style={{width:`${capacityPercent}%`}}/></div></div></button>})}</div>{selected&&<div className="modalback" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="modal warehouse-modal" role="dialog" aria-modal="true" aria-labelledby="warehouse-title"><div className="modalhead"><div><h2 id="warehouse-title">{selected}</h2><small>Розничная стоимость остатков: <strong>{money(retailTotal)}</strong></small></div><button className="close" aria-label="Закрыть склад" onClick={()=>setSelected(null)}><X/></button></div><div className="warehouse-stock-body">{loading?<p className="stock-state">Загружаем остатки...</p>:error?<p className="form-error" role="alert">{error}</p>:stocks.length===0?<p className="stock-state">На этом складе пока нет товарных позиций</p>:<><StockTable title="Товары на складе" stocks={stocks} open={showMovements}/><LogisticsTable title="Поступающие товары" batches={incoming} mode="incoming" onMovements={onMovements}/><LogisticsTable title="Запланированные отправки" batches={outgoing} mode="outgoing" onMovements={onMovements}/></>}<aside className="warehouse-note"><div><small>Приблизительная вместимость</small><strong>~{selectedUsed} / {selectedTotal} ед.</strong></div><p><strong>Замечание складовщика:</strong> {selectedNote}</p></aside></div></section></div>}</>
}

function StockTable({title,stocks,open}:{title:string;stocks:Stock[];open:(product:Stock,mode:"stock"|"incoming"|"outgoing")=>void}){
 const sum=(pick:(x:Stock)=>number)=>stocks.reduce((total,item)=>total+pick(item),0),quantity=sum(x=>x.quantity),purchaseValue=sum(x=>x.purchaseValue),weightedPrice=quantity?purchaseValue/quantity:0;
 return <section className="warehouse-stock-section"><h3>{title}</h3><div className="table-scroll"><table className="table"><thead><tr><th>Товар</th><th>Артикул</th><th>Доступно</th><th>К отправке</th><th>Останется после отправок</th><th>Закупочная цена</th><th>Сумма закупки</th><th>Розничная стоимость</th></tr></thead><tbody>{stocks.map(x=><tr className="clickable-row" tabIndex={0} key={x.id} onClick={()=>open(x,"stock")} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open(x,"stock")}}}><td><span className="product-identity"><strong>{x.productName}</strong><small>SKU: {x.sku}</small></span></td><td><span className="product-identity"><strong>{x.sku}</strong><small>{x.productName}</small></span></td><td>{x.quantity} ед.</td><td>{x.expectedOutgoing} ед.</td><td><strong>{x.remainingAfterOutgoing} ед.</strong></td><td>{money(x.purchasePrice)}</td><td>{money(x.purchaseValue)}</td><td><strong>{money(x.retailValue)}</strong></td></tr>)}</tbody><tfoot><tr className="warehouse-total-row"><th>Итого</th><td>{stocks.length} позиций</td><td>{quantity} ед.</td><td>{sum(x=>x.expectedOutgoing)} ед.</td><td>{sum(x=>x.remainingAfterOutgoing)} ед.</td><td><span>Средняя: {money(weightedPrice)}</span></td><td>{money(purchaseValue)}</td><td><strong>{money(sum(x=>x.retailValue))}</strong></td></tr></tfoot></table></div></section>
}

function LogisticsTable({title,batches,mode,onMovements}:{title:string;batches:Movement[];mode:"incoming"|"outgoing";onMovements:(filter:string)=>void}){
 return <section className="warehouse-stock-section"><h3>{title}</h3>{batches.length===0?<p className="stock-state">Нет запланированных операций</p>:<div className="table-scroll"><table className="table"><thead><tr><th>Товар</th><th>Документ</th><th>Партия</th><th>Откуда</th><th>Куда</th><th>Дата</th><th>Количество</th><th>Статус</th></tr></thead><tbody>{batches.map(x=>{const params=new URLSearchParams({sku:x.productSku,warehouse:mode==="incoming"?x.destination:x.source,operation:mode,batch:x.batchNumber});return <tr className="clickable-row" tabIndex={0} key={x.id} onClick={()=>onMovements(params.toString())} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();onMovements(params.toString())}}}><td><span className="product-identity"><strong>{x.productName||x.productSku||"-"}</strong>{x.productSku&&<small>SKU: {x.productSku}</small>}</span></td><td>{x.number}</td><td>{x.batchNumber||"-"}</td><td>{x.source}</td><td>{x.destination}</td><td>{x.date}</td><td>{x.quantity} ед.</td><td>{x.status}</td></tr>})}</tbody></table></div>}</section>
}
