"use client";
import {Store,Warehouse,X} from "lucide-react";
import {useEffect,useState} from "react";
import type {Company} from "../lib/types";
import {API_URL} from "../lib/api";
import {ProductTraceModal} from "./ProductTraceModal";

type Stock={id:number;warehouseName:string;sku:string;productName:string;quantity:number;expectedIncoming:number;expectedOutgoing:number;retailPrice:number;retailValue:number};
const money=(value:number)=>`${value.toLocaleString("ru-RU")} сум`;

export function WarehousesPage({rows,company}:{rows:string[][];company:Company}){
 const [selected,setSelected]=useState<string|null>(null),[selectedProduct,setSelectedProduct]=useState<{sku:string;name:string}|null>(null),[stocks,setStocks]=useState<Stock[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 function openWarehouse(name:string){setLoading(true);setError("");setStocks([]);setSelected(name)}
 useEffect(()=>{if(!selected)return;const controller=new AbortController();fetch(`${API_URL}/api/warehouse-stocks/valuation?scope=${company}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((items:Stock[])=>setStocks(items.filter(x=>x.warehouseName===selected))).catch(e=>{if(e.name!=="AbortError")setError("Не удалось загрузить остатки склада")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[selected,company]);
 useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[selected]);
 const retailTotal=stocks.reduce((sum,item)=>sum+item.retailValue,0);
 return <><div className="toolbar"><span className={`business-chip company-${company}`}>{rows.length} складских точек</span><span className="spacer"/><span className="count">Нажми на склад, затем на товар</span></div><div className="warehouse-grid">{rows.map(w=><button className="card warehouse warehouse-button" key={w[0]} onClick={()=>openWarehouse(w[0])}><div className="warehouse-head"><span className="warehouse-icon">{/магазин/i.test(w[0])?<Store/>:<Warehouse/>}</span><span className="badge">Активен</span></div><h3>{w[0]}</h3><p>{w[1]}</p><div className="warehouse-stats"><div className="mini"><small>Остаток</small><strong>{w[2]} ед.</strong></div><div className="mini"><small>Учетная стоимость</small><strong>{w[3]}</strong></div></div><div style={{marginTop:10}}><div className="progress"><span style={{width:w[4]}}/></div></div></button>)}</div>{selected&&<div className="modalback" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="modal warehouse-modal" role="dialog" aria-modal="true" aria-labelledby="warehouse-title"><div className="modalhead"><div><h2 id="warehouse-title">{selected}</h2><small>Розничная стоимость остатков: <strong>{money(retailTotal)}</strong></small></div><button className="close" aria-label="Закрыть склад" onClick={()=>setSelected(null)}><X/></button></div><div className="warehouse-stock-body">{loading?<p className="stock-state">Загружаем остатки...</p>:error?<p className="form-error" role="alert">{error}</p>:stocks.length===0?<p className="stock-state">На этом складе пока нет товарных позиций</p>:<div className="table-scroll"><table className="table"><thead><tr><th>Товар</th><th>Артикул</th><th>Количество</th><th>Розничная цена</th><th>Сумма</th><th>Ожидается</th><th>К отправке</th></tr></thead><tbody>{stocks.map(x=><tr className="clickable-row" tabIndex={0} key={x.id} onClick={()=>setSelectedProduct({sku:x.sku,name:x.productName})} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelectedProduct({sku:x.sku,name:x.productName})}}}><td><strong>{x.productName}</strong></td><td>{x.sku}</td><td>{x.quantity} ед.</td><td>{money(x.retailPrice)}</td><td><strong>{money(x.retailValue)}</strong></td><td>{x.expectedIncoming} ед.</td><td>{x.expectedOutgoing} ед.</td></tr>)}</tbody></table></div>}</div></section></div>}{selectedProduct&&<ProductTraceModal {...selectedProduct} company={company} onClose={()=>setSelectedProduct(null)}/>}</>
}
